const myService = [
  {
    'gmtModified': '2018-11-22 11:02:37',
    'code': 'S01ZL0XUKO0',
    'accessUrl': 'http',
    'name': '公积金查询',
    'unifiedCode': null,
    'description': null,
    'id': 1,
    'type': null,
    'gmtCreate': '2018-11-07 13:37:06',
    'logoUrl': 'https://gw.alipayobjects.com/zos/rmsportal/KAcsudEtZqUEXWIdErmN.png',
    'status': 'PENDING_APPROVE',
  },
  {
    'gmtModified': '2018-11-19 16:31:55',
    'code': 'S01ZL0XUKO1',
    'accessUrl': 'http',
    'name': '公积金查询',
    'unifiedCode': null,
    'description': null,
    'id': 2,
    'type': null,
    'gmtCreate': '2018-11-07 13:37:04',
    'logoUrl': 'https://gw.alipayobjects.com/zos/rmsportal/mcAuSIDEdSwjoIiotMrt.png',
    'status': null,
  },
  {
    'gmtModified': '2018-11-19 16:31:55',
    'code': 'S01ZL0XUKO1',
    'accessUrl': 'http',
    'name': '公积金查询',
    'unifiedCode': null,
    'description': null,
    'id': 3,
    'type': null,
    'gmtCreate': '2018-11-07 13:37:04',
    'logoUrl': 'https://gw.alipayobjects.com/zos/rmsportal/KAcsudEtZqUEXWIdErmN.png',
    'status': null,
  },
  {
    'gmtModified': '2018-11-19 16:31:55',
    'code': 'S01ZL0XUKO1',
    'accessUrl': 'http',
    'name': '公积金查询',
    'unifiedCode': null,
    'description': null,
    'id': 4,
    'type': null,
    'gmtCreate': '2018-11-07 13:37:04',
    'logoUrl': 'https://gw.alipayobjects.com/zos/rmsportal/mcAuSIDEdSwjoIiotMrt.png',
    'status': null,
  },
  {
    'gmtModified': '2018-11-19 16:31:55',
    'code': 'S01ZL0XUKO1',
    'accessUrl': 'http',
    'name': '公积金查询',
    'unifiedCode': null,
    'description': null,
    'id': 5,
    'type': null,
    'gmtCreate': '2018-11-07 13:37:04',
    'logoUrl': 'https://gw.alipayobjects.com/zos/rmsportal/KAcsudEtZqUEXWIdErmN.png',
    'status': null,
  },
  {
    'gmtModified': '2018-11-19 16:31:55',
    'code': 'S01ZL0XUKO1',
    'accessUrl': 'http',
    'name': '公积金查询',
    'unifiedCode': null,
    'description': null,
    'id': 6,
    'type': null,
    'gmtCreate': '2018-11-07 13:37:04',
    'logoUrl': 'https://gw.alipayobjects.com/zos/rmsportal/mcAuSIDEdSwjoIiotMrt.png',
    'status': null,
  },
  {
    'gmtModified': '2018-11-19 16:31:55',
    'code': 'S01ZL0XUKO1',
    'accessUrl': 'http',
    'name': '公积金查询',
    'unifiedCode': null,
    'description': null,
    'id': 7,
    'type': null,
    'gmtCreate': '2018-11-07 13:37:04',
    'logoUrl': 'https://gw.alipayobjects.com/zos/rmsportal/KAcsudEtZqUEXWIdErmN.png',
    'status': null,
  },
];
export default myService;

