export default [
  {
    'id': '20181201111000907053079989',
    'code': 'HAINAN_index',
    'areaCode': '320200',
    'pageInstanceId': '20181201111300799525570470',
    'pageBlock': {
      'pageId': null,
      'pageInstanceId': '20181201111300799525570470',
      'status': null,
      'version': null,
      'blockList': [
        {
          'blockId': '201811231103239893444444',
          'blockType': 'STATIC',
          'realType': 'STATIC',
          'blockCode': '',
          'blockName': '系统公告',
          'blockStyle': 'tpl-information',
          'blockParams': null,
          'blockElementList': [
            {
              'image': 'https://gw.alipayobjects.com/zos/rmsportal/NznxJWjTIPrpWFAvAVSh.png',
              'desc': '首张全国统一电子社保卡来了 七大便民功能即将上线',
              'url': 'http://www.tmall.com',
            },
          ],
        },
        {
          'blockId': '201811231103239893444444',
          'blockType': 'STATIC',
          'realType': 'STATIC',
          'blockCode': 'tpl-servicecenter',
          'blockName': '推荐服务',
          'blockStyle': 'tpl-servicecenter',
          'blockParams': [
            {
              'elementKey': 'serviceType',
              'elementName': '',
              'elementValue': 'recommendservice',
            },
          ],
          'blockElementList': [{
            name: '掌上咨询',
            url: '',
            logoUrl: 'https://gw.alipayobjects.com/zos/rmsportal/WNiXvZKojdRvFQdhnCKh.png',
          }, {
            name: '办事指南',
            url: '',
            logoUrl: 'https://gw.alipayobjects.com/zos/rmsportal/ocJzfTKOFRGfBDnwmXKV.png',
          }, {
            name: '投诉举报',
            url: '',
            logoUrl: 'https://gw.alipayobjects.com/zos/rmsportal/mcAuSIDEdSwjoIiotMrt.png',
          }, {
            name: '平安随手拍',
            url: '',
            logoUrl: 'https://gw.alipayobjects.com/zos/rmsportal/KAcsudEtZqUEXWIdErmN.png',
          }],
        },
        {
          'blockId': '201811231103239893444444',
          'blockType': 'STATIC',
          'realType': 'STATIC',
          'blockCode': 'tpl-credentials',
          'blockName': '我的证件',
          'blockStyle': 'tpl-credentials',
          'blockParams': [{
            'elementKey': 'moreTest',
            'elementName': '',
            'elementValue': '全部证件',
          },
          {
            'elementKey': 'moreTextUrl',
            'elementName': '',
            'elementValue': 'http://baidu.com',
          },
          {
            'elementKey': 'indicatorDots',
            'elementName': '',
            'elementValue': true,
          },
          {
            'elementKey': 'autoplay',
            'elementName': '',
            'elementValue': false,
          },
          {
            'elementKey': 'interval',
            'elementName': '',
            'elementValue': 3000,
          },
          ],
          'blockElementList': [
            {
              'image': 'https://gw.alipayobjects.com/zos/rmsportal/CTaOcdoWQmleGgUQUIzr.png',
              'title': '社会保障卡1',
              'subtitle': '浙江省人力资源和社会保障厅',
              'desc': '查社保、缴社保、付医保',
            },
            {
              'image': 'https://gw.alipayobjects.com/zos/rmsportal/CTaOcdoWQmleGgUQUIzr.png',
              'title': '社会保障卡2',
              'subtitle': '浙江省人力资源和社会保障厅',
              'desc': '查社保、缴社保、付医保',
            },
            {
              'image': 'https://gw.alipayobjects.com/zos/rmsportal/CTaOcdoWQmleGgUQUIzr.png',
              'title': '社会保障卡3',
              'subtitle': '浙江省人力资源和社会保障厅',
              'desc': '查社保、缴社保、付医保',
            },
          ],
        },
        {
          'blockId': '201811231103239893444444',
          'blockType': 'STATIC',
          'realType': 'STATIC',
          'blockCode': 'tpl-servicecenter',
          'blockName': '我的服务',
          'blockStyle': 'tpl-servicecenter',
          'blockParams': [
            {
              'elementKey': 'serviceType',
              'elementName': '',
              'elementValue': 'myservice',
            },
          ],
          'blockElementList': [
            {
              'gmtModified': '2018-11-22 11:02:37',
              'code': 'S01ZL0XUKO0',
              'url': '/pages/market/index',
              'name': '公积金查询',
              'unifisedCode': null,
              'description': null,
              'id': 1,
              'type': null,
              'gmtCreate': '2018-11-07 13:37:06',
              'logoUrl': 'https://gw.alipayobjects.com/zos/rmsportal/KAcsudEtZqUEXWIdErmN.png',
              'status': 'PENDING_APPROVE',
            },
            {
              'gmtModified': '2018-11-19 16:31:55',
              'code': 'S01ZL0XUKO1',
              'url': 'http',
              'name': '公积金查询',
              'unifiedCode': null,
              'description': null,
              'id': 2,
              'type': null,
              'gmtCreate': '2018-11-07 13:37:04',
              'logoUrl': 'https://gw.alipayobjects.com/zos/rmsportal/mcAuSIDEdSwjoIiotMrt.png',
              'status': null,
            },
            {
              'gmtModified': '2018-11-19 16:31:55',
              'code': 'S01ZL0XUKO1',
              'url': 'http',
              'name': '公积金查询',
              'unifiedCode': null,
              'description': null,
              'id': 3,
              'type': null,
              'gmtCreate': '2018-11-07 13:37:04',
              'logoUrl': 'https://gw.alipayobjects.com/zos/rmsportal/KAcsudEtZqUEXWIdErmN.png',
              'status': null,
            },
            {
              'gmtModified': '2018-11-19 16:31:55',
              'code': 'S01ZL0XUKO1',
              'url': 'http',
              'name': '公积金查询',
              'unifiedCode': null,
              'description': null,
              'id': 4,
              'type': null,
              'gmtCreate': '2018-11-07 13:37:04',
              'logoUrl': 'https://gw.alipayobjects.com/zos/rmsportal/mcAuSIDEdSwjoIiotMrt.png',
              'status': null,
            },
            {
              'gmtModified': '2018-11-19 16:31:55',
              'code': 'S01ZL0XUKO1',
              'url': 'http',
              'name': '公积金查询',
              'unifiedCode': null,
              'description': null,
              'id': 5,
              'type': null,
              'gmtCreate': '2018-11-07 13:37:04',
              'logoUrl': 'https://gw.alipayobjects.com/zos/rmsportal/KAcsudEtZqUEXWIdErmN.png',
              'status': null,
            },
            {
              'gmtModified': '2018-11-19 16:31:55',
              'code': 'S01ZL0XUKO1',
              'url': 'http',
              'name': '公积金查询',
              'unifiedCode': null,
              'description': null,
              'id': 6,
              'type': null,
              'gmtCreate': '2018-11-07 13:37:04',
              'logoUrl': 'https://gw.alipayobjects.com/zos/rmsportal/mcAuSIDEdSwjoIiotMrt.png',
              'status': null,
            },
            {
              'gmtModified': '2018-11-19 16:31:55',
              'code': 'S01ZL0XUKO1',
              'url': 'http',
              'name': '公积金查询',
              'unifiedCode': null,
              'description': null,
              'id': 7,
              'type': null,
              'gmtCreate': '2018-11-07 13:37:04',
              'logoUrl': 'https://gw.alipayobjects.com/zos/rmsportal/KAcsudEtZqUEXWIdErmN.png',
              'status': null,
            },
            {
              'gmtModified': '2018-11-19 16:31:55',
              'code': 'S01ZL0XUKO1',
              'url': 'market',
              'name': '更多服务',
              'unifiedCode': null,
              'description': null,
              'id': 314,
              'type': null,
              'gmtCreate': '2018-11-07 13:37:04',
              'logoUrl': 'https://gw.alipayobjects.com/zos/rmsportal/KAcsudEtZqUEXWIdErmN.png',
              'status': null,
            },
          ],
        },
        {
          'blockId': '201811231103239893444444',
          'blockType': 'STATIC',
          'realType': 'STATIC',
          'blockCode': 'tpl-servicecard',
          'blockName': '社保',
          'blockStyle': 'tpl-servicecard',
          'blockParams': [
            {
              'elementKey': 'icon',
              'elementName': '',
              'elementValue': 'https://gw.alipayobjects.com/zos/rmsportal/VQyMeGAHDZExKbXAxect.png',
            },
            {
              'elementKey': 'desc',
              'elementName': '',
              'elementValue': '杭州市人力资源和社会保障局  提供6项服务',
            }, {
              'elementKey': 'url',
              'elementName': '',
              'elementValue': '/pages/index/index',
            },
          ],
          'blockElementList': [[{
            name: '缴存明细',
            url: '',
          }, {
            name: '缴社保',
            url: '',
          }], [{
            name: '社保证明',
            url: '',
          }, {
            name: '电子社保卡',
            url: '',
          }]],
        },
        {
          'blockId': '201811231103239893444444',
          'blockType': 'STATIC',
          'realType': 'STATIC',
          'blockCode': 'tpl-servicecard',
          'blockName': '公积金',
          'blockStyle': 'tpl-servicecard',
          'blockParams': [
            {
              'elementKey': 'icon',
              'elementName': '',
              'elementValue': 'https://gw.alipayobjects.com/zos/rmsportal/VQyMeGAHDZExKbXAxect.png',
            },
            {
              'elementKey': 'desc',
              'elementName': '',
              'elementValue': '杭州市人力资源和社会保障局  提供6项服务',
            }, {
              'elementKey': 'url',
              'elementName': '',
              'elementValue': '/pages/index/index',
            },
          ],
          'blockElementList': [[{
            name: '杭州公积金',
            url: '',
          }, {
            name: '住房公积金',
            url: '',
          }], [{
            name: '公积金查询',
            url: '',
          }]],
        },
        {
          'blockId': '201811231103239893444444',
          'blockType': 'STATIC',
          'realType': 'STATIC',
          'blockCode': 'tpl-servicecard',
          'blockName': '交通出行',
          'blockStyle': 'tpl-servicecard',
          'blockParams': [
            {
              'elementKey': 'icon',
              'elementName': '',
              'elementValue': 'https://gw.alipayobjects.com/zos/rmsportal/VQyMeGAHDZExKbXAxect.png',
            },
            {
              'elementKey': 'desc',
              'elementName': '',
              'elementValue': '杭州市人力资源和社会保障局  提供6项服务',
            }, {
              'elementKey': 'url',
              'elementName': '',
              'elementValue': '/pages/index/index',
            },
          ],
          'blockElementList': [[{
            name: '交通违法处理',
            url: '',
          }, {
            name: '车辆事故处理',
            url: '',
          }], [{
            name: '违章查询',
            url: '',
          }, {
            name: '证件补办',
            url: '',
          }]],
        },
        // {
        //   'blockId': '201811231103892484874744',
        //   'blockType': 'SERVICE',
        //   'realType': 'SERVICE',
        //   'blockCode': 'tpl-credentials',
        //   'blockName': '常用服务',
        //   'blockStyle': null,
        //   'blockParams': null,
        //   'blockElementList': [
        //     {
        //       'id': '201811071101003170628497',
        //       'name': '驾驶证补换',
        //       'code': 'S01ZL0XUKO6',
        //       'unifiedCode': null,
        //       'description': null,
        //       'status': 'ONLINE',
        //       'url': 'http://baidu.com',
        //       'logoUrl': null,
        //       'type': null,
        //       'gmtCreate': '2018-11-07 13:37:02',
        //       'gmtModified': '2018-11-23 17:23:38'
        //     },
        //     {
        //       'id': '201811071101003170628498',
        //       'name': '公共支付',
        //       'code': 'S01ZL0XUKO7',
        //       'unifiedCode': null,
        //       'description': null,
        //       'status': 'ONLINE',
        //       'url': 'http://baidu.com',
        //       'logoUrl': null,
        //       'type': null,
        //       'gmtCreate': '2018-11-07 13:37:01',
        //       'gmtModified': '2018-11-23 17:23:27'
        //     }
        //   ]
        // }
      ],
    },
  },
  {
    'id': '2018120111100022461112370',
    'code': 'HAINAN_in2dex',
    'areaCode': '320200',
    'pageInstanceId': '20181201111300912960596627',
    'pageBlock': {
      'pageId': null,
      'pageInstanceId': '20181201111300912960596627',
      'status': null,
      'version': null,
      'blockList': [
        {
          'blockId': '20181201110400349405378823',
          'blockType': 'SERVICE',
          'realType': 'SERVICE',
          'blockCode': 'teaeff',
          'blockName': 'tafasfdad',
          'blockStyle': null,
          'blockParams': null,
          'blockElementList': [
            {
              'id': '20181201110100582733802887',
              'name': '2019',
              'code': '叽叽叽',
              'unifiedCode': 'iii交大附近',
              'description': null,
              'status': 'ONLINE',
              'accessUrl': '3333',
              'logoUrl': 'http://urcappdev.alipay-eco.com/upload/image/1543648833654.png',
              'type': '',
              'gmtCreate': '2018-12-01 15:20:36',
              'gmtModified': '2018-12-01 21:01:58',
            },
          ],
        },
      ],
    },
  },
];
